set --universal --unpath --unexport _fish_abbr_ag 'ag --ignore-case'
set --universal --unpath --unexport _fish_abbr_agp 'ag --ignore-case --pager="less -iMR"'
set --universal --unpath --unexport _fish_abbr_cp 'cp -i'
set --universal --unpath --unexport _fish_abbr_d 'icdiff'
set --universal --unpath --unexport _fish_abbr_df 'df -h'
set --universal --unpath --unexport _fish_abbr_diff 'icdiff'
set --universal --unpath --unexport _fish_abbr_du 'du -h'
set --universal --unpath --unexport _fish_abbr_ga 'git add'
set --universal --unpath --unexport _fish_abbr_gb 'git branch'
set --universal --unpath --unexport _fish_abbr_gbal 'git branch -al'
set --universal --unpath --unexport _fish_abbr_gc 'git commit --verbose'
set --universal --unpath --unexport _fish_abbr_gca 'git commit --all --verbose'
set --universal --unpath --unexport _fish_abbr_gco 'git checkout'
set --universal --unpath --unexport _fish_abbr_gd 'git diff'
set --universal --unpath --unexport _fish_abbr_gdc 'git diff --cached'
set --universal --unpath --unexport _fish_abbr_glg 'git log --stat=300,300 --stat-graph-width=20'
set --universal --unpath --unexport _fish_abbr_glgp 'git log --stat=300,300 --stat-graph-width=20 --patch'
set --universal --unpath --unexport _fish_abbr_grep 'grep -i'
set --universal --unpath --unexport _fish_abbr_gst 'git status'
set --universal --unpath --unexport _fish_abbr_gsw 'git switch'
set --universal --unpath --unexport _fish_abbr_gswc 'git switch -c'
set --universal --unpath --unexport _fish_abbr_k 'kubectl'
set --universal --unpath --unexport _fish_abbr_less 'less -iMR'
set --universal --unpath --unexport _fish_abbr_lla 'ls -al'
set --universal --unpath --unexport _fish_abbr_mv 'mv -i'
set --universal --unpath --unexport _fish_abbr_mycli 'mycli --warn'
set --universal --unpath --unexport _fish_abbr_tree 'tree -CN'
set --universal --unpath --unexport fish_color_autosuggestion '555' 'brblack'
set --universal --unpath --unexport fish_color_cancel '-r'
set --universal --unpath --unexport fish_color_command '005fd7'
set --universal --unpath --unexport fish_color_comment '990000'
set --universal --unpath --unexport fish_color_cwd 'green'
set --universal --unpath --unexport fish_color_cwd_root 'red'
set --universal --unpath --unexport fish_color_end '009900'
set --universal --unpath --unexport fish_color_error 'ff0000'
set --universal --unpath --unexport fish_color_escape '00a6b2'
set --universal --unpath --unexport fish_color_history_current '--bold'
set --universal --unpath --unexport fish_color_host 'normal'
set --universal --unpath --unexport fish_color_host_remote 'yellow'
set --universal --unpath --unexport fish_color_normal 'normal'
set --universal --unpath --unexport fish_color_operator '00a6b2'
set --universal --unpath --unexport fish_color_param '00afff'
set --universal --unpath --unexport fish_color_quote '999900'
set --universal --unpath --unexport fish_color_redirection '00afff'
set --universal --unpath --unexport fish_color_search_match 'bryellow' '--background=brblack'
set --universal --unpath --unexport fish_color_selection 'white' '--bold' '--background=brblack'
set --universal --unpath --unexport fish_color_status 'red'
set --universal --unpath --unexport fish_color_user 'brgreen'
set --universal --unpath --unexport fish_color_valid_path '--underline'
set --universal --unpath --unexport fish_key_bindings 'fish_default_key_bindings'
set --universal --unpath --unexport fish_pager_color_completion 
set --universal --unpath --unexport fish_pager_color_description 'B3A06D' 'yellow'
set --universal --unpath --unexport fish_pager_color_prefix 'normal' '--bold' '--underline'
set --universal --unpath --unexport fish_pager_color_progress 'brwhite' '--background=cyan'
set --universal --unpath --unexport fish_pager_color_selected_background '-r'
