set --universal --unpath --unexport __fish_initialized '3100'
set --universal --unpath --unexport fish_color_autosuggestion '555' 'brblack'
set --universal --unpath --unexport fish_color_cancel '-r'
set --universal --unpath --unexport fish_color_command '005fd7'
set --universal --unpath --unexport fish_color_comment '990000'
set --universal --unpath --unexport fish_color_cwd 'green'
set --universal --unpath --unexport fish_color_cwd_root 'red'
set --universal --unpath --unexport fish_color_end '009900'
set --universal --unpath --unexport fish_color_error 'ff0000'
set --universal --unpath --unexport fish_color_escape '00a6b2'
set --universal --unpath --unexport fish_color_history_current '--bold'
set --universal --unpath --unexport fish_color_host 'normal'
set --universal --unpath --unexport fish_color_host_remote 'yellow'
set --universal --unpath --unexport fish_color_normal 'normal'
set --universal --unpath --unexport fish_color_operator '00a6b2'
set --universal --unpath --unexport fish_color_param '00afff'
set --universal --unpath --unexport fish_color_quote '999900'
set --universal --unpath --unexport fish_color_redirection '00afff'
set --universal --unpath --unexport fish_color_search_match 'bryellow' '--background=brblack'
set --universal --unpath --unexport fish_color_selection 'white' '--bold' '--background=brblack'
set --universal --unpath --unexport fish_color_status 'red'
set --universal --unpath --unexport fish_color_user 'brgreen'
set --universal --unpath --unexport fish_color_valid_path '--underline'
set --universal --unpath --unexport fish_key_bindings 'fish_default_key_bindings'
set --universal --unpath --unexport fish_pager_color_completion 
set --universal --unpath --unexport fish_pager_color_description 'B3A06D' 'yellow'
set --universal --unpath --unexport fish_pager_color_prefix 'normal' '--bold' '--underline'
set --universal --unpath --unexport fish_pager_color_progress 'brwhite' '--background=cyan'
